builds:
  - binary: skipgen
    goos:
      - linux
    goarch:
      - amd64
      - arm
      - arm64
      - i386
    goarm:
      - 6
      - 7
    hooks:
      post: find . -name skipgen -exec upx {} +
