language: go

go:
  - 1.9.x

addons:
  apt:
    packages:
      - upx

before_install:
  - go get -v github.com/golang/lint/golint
  - go get -t ./...

script:
  - make test

after_success:
  - test -n "$TRAVIS_TAG" && curl -sL https://git.io/goreleaser | bash
